### ISSUE TITLE
Asset files

### ISSUE THREAD

**Issue by nirtamir2** [Laupetin/Lego-Racers-Mod#16]
Hi
I wonder if it's possible to have the Lego Racers assets as OBJ or format that blender can open (gltf is the best)?
I want to look over them and build stuff with them without the need to install things on my computer
If you have them - can you add them to the repository (even in a separate branch)
Thank you!

**Comment by Laupetin** [comment]
Hey,
the repository contains tools to extract the LEGO.JAM file into its contents which contains the models in LR's own proprietary GDB format.
The converter tool can then convert this into OBJ files. GLTF is not supported yet, i started on that feature but did not finish it.
So you can just use the tools here to dump these files yourself.

I won't upload the assets themselves to the repo though because:
* Even if it's unlikely for somebody to care in this exact case due to the age and availability of this game: I don't own the rights to publish these assets. So I don't do that for any games I mod.
* Game assets are much larger than code making the size of the repository a lot larger in comparison than it would usually be
* The models themselves reference textures in their materials which are also dumped. If i were to just upload the models, they would reference textures that are not there.
* I don't want to update an asset dump anytime a change happens to dumping code, changing the output. It would also mean that there would have to be a dump in all kinds of formats that are there if gltf is implemented at some point. It also doesn't really fit the purpose of this project/repository.

So I'm afraid you will have to dump them yourself. If you don't want to install anything on your machine you can also use a VM.
That also only applies to the game itself. The tools in this repository do not require an installation and also run under linux.

**Comment by nirtamir2** [comment]
Thanks 🙏
I have a development environment on my Mac
Is it possible to get it running?

**Comment by Laupetin** [comment]
I'm afraid i don't know a whole lot about Macs :/ I don't have nor ever had one. So i can't really give you any tips on that, sorry D:
